### ISSUE TITLE
Create Landscape Page

### ISSUE THREAD

**Issue by charlieroth** [charlieroth/gol_engine_web#1]
### Tasks
- [ ] Create clickable grid of cells
- [ ] Create connect button
- [ ] Create seed button
- [ ] Create run button
