### ISSUE TITLE
Implement HTTP/WS Communications

### ISSUE THREAD

**Issue by charlieroth** [charlieroth/gol_engine_web#2]
## Purpose
The line of communication between Client and Server

## Tasks
- [ ] Implement WS Connection
- [ ] Implement connect event
- [ ] Implement seed event
- [ ] Implement run event
- [ ] Implement evolve event
